### ISSUE TITLE
Crash upon trying to click on the settings of the mod in mod options

### ISSUE THREAD

**Issue by Kunnoc** [rockymoto517/bad-apple-preplanning#1]
Application has crashed: C++ exception
[string "lib/managers/menu/items/menuitemmultichoice.lua"]:279: attempt to index a nil value

SCRIPT STACK

reload_item() lib/managers/menu/menunodegui.lua:1098
_setup_item_rows() core/lib/managers/menu/reference_renderer/coremenunodegui.lua:149
init() core/lib/managers/menu/reference_renderer/coremenunodegui.lua:64
init() lib/managers/menu/menunodegui.lua:68
new() core/lib/utils/coreclass.lua:35
show_node() core/lib/managers/menu/reference_renderer/coremenurenderer.lua:81
lib/managers/menu/menurenderer.lua:70
_call_callback() core/lib/managers/menu/coremenulogic.lua:331
core/lib/managers/menu/coremenulogic.lua:96
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:909
update() @mods/base/req/core/Hooks.lua:264
original() lib/setups/menusetup.lua:361
update() @mods/base/req/core/Hooks.lua:264
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath

**Comment by rockymoto517** [comment]
Could you tell me how exactly you're crashing, I just played the mod again and I didn't get a crash.

**Comment by Kunnoc** [comment]
I got it when I tried going to the mod options to try and change the keybinds. I tried deleting all the other mods reinstall beardlib still crashing.

**Comment by rockymoto517** [comment]
Oh I see the issue, I forgot to remove the mod options field I created for an alternate version of this mod. You should be changing the keybind in the 'mod keybinds' menu instead of mod options. 

p.s. this mod doesn't require beardlib
